package com.test;

import com.mysql.cj.jdbc.MysqlDataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;

@Service
public class UserService {

    /**
     * It can be achieved using Platform TransactionManger or Transaction Template
     */

    @Autowired
    private TransactionTemplate template;
    public Long registerUser(User user) {
        Long id = template.execute(status ->  {
            // execute some SQL that e.g.
            //inserts the user into the db and returns the autogenerated id

            return null;
        });
        return id;
    }

    @Bean
    public DataSource dataSource() {
        return new MysqlDataSource(); // (1)
    }

    @Bean
    public PlatformTransactionManager txManager() {
        return new DataSourceTransactionManager(dataSource()); // (2)
    }
}




class User{

}